# -*- coding: utf-8 -*-
"""AnalyzingEmotioninFakeNews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yAsWQ6oXrzJqKrwBWFULrCd54UIaFFZm
"""

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("cleaned_dataset.csv")

data.head()

nltk.download('vader_lexicon')

analyzer = SentimentIntensityAnalyzer()

def analyze_sentiment(text):
  sentiment_score = analyzer.polarity_scores(text)
  if sentiment_score["compound"] >= 0.05:
    return "Positive"
  elif sentiment_score["compound"] <= -0.05:
    return "Negative"
  else:
    return "Neutral"

data["Sentiment"] = data["text"].apply(analyze_sentiment)

print(data[['text','Sentiment']].head())