# -*- coding: utf-8 -*-
"""DetectingSensationalisminFakeNews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xvPqKq04n2FLEgtNjJ6GF6GYH1aceqHI
"""

import pandas as pd
from google.colab import files
from scipy.stats import chi2_contingency

uploaded = files.upload()

data = pd.read_csv("cleaned_dataset.csv")

data.head()

def detect_sensationalism(text):
    sensational_keywords = ["shocking", "outrageous", "unbelievable", "mind-blowing", "explosive"]

    for keyword in sensational_keywords:
        if re.search(r'\b' + keyword + r'\b', text, re.IGNORECASE):
            return True
    return False

data["Sensationalism"] = data["text"].apply(detect_sensationalism)

contigency_table = pd.crosstab(data["Sensationalism"],data["label"])
print(contigency_table)

chi2,p,_,_ = chi2_contingency(contigency_table)

print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")

alpha = 0.05
if p < alpha:
  print("There is a significant association between sensationalism and credibility of the news")
else:
  print("There is not significant association between sensationalism and credibility of the news")