# -*- coding: utf-8 -*-
"""NewsSourceCredibilityAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qbvjg61UYlaPoy4MuHV_Obfqe4EJ5vjQ
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("cleaned_dataset.csv")

data.head()

source_counts = data.groupby(["site_url","label"]).size().unstack(fill_value=0)

source_counts["Percentage Real (%)"] = (source_counts["Real"]/(source_counts["Real"]+source_counts["Fake"])) * 100
source_counts["Percentage Fake (%)"] = (source_counts["Fake"]/(source_counts["Real"]+source_counts["Fake"])) * 100

sorted_sources = source_counts.sort_values(by="Percentage Real (%)", ascending=False)

print("Top 10 Most Credible News Sources:")
for source, row in sorted_sources.head(10).iterrows():
  print(f"News {source}, fake news = {row['Percentage Fake (%)']:.1f}%")

print("Top 10 Least Credible News Sources:")
for source, row in sorted_sources.tail(10).iterrows():
  print(f"News {source}, fake news = {row['Percentage Fake (%)']:.1f}%")