# -*- coding: utf-8 -*-
"""NewsTitle&TextLengthAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uD5Dr5VZiFB1g3ioCDLChSPFglFhmJ9y
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

data = pd.read_csv("cleaned_dataset.csv")

data.head()

data["title_length"] = data["title"].apply(len)
data["text_length"] = data["text"].apply(len)

real_news = data[data["label"]=="Real"]
fake_news = data[data["label"]=="Fake"]

avg_real_title_length = real_news["title_length"].mean()
avg_fake_title_length = fake_news["title_length"].mean()
avg_real_text_length = real_news["text_length"].mean()
avg_fake_text_length = fake_news["text_length"].mean()

print(f"Average Title Length for Real News: {avg_real_title_length:.2f} characters")
print(f"Average Title Length for Fake News: {avg_fake_title_length:.2f} characters")
print(f"Average Text Length for Real News: {avg_real_text_length:.2f} characters")
print(f"Average Text Length for Fake News: {avg_fake_text_length:.2f} characters")

labels = ["Real Title","Fake News","Real Text","Fake Text"]
lengths = [avg_real_title_length, avg_fake_title_length, avg_real_text_length,avg_fake_text_length ]

plt.figure(figsize=(10,6))
plt.bar(labels,lengths,color=["green","red","green","red"])
plt.title("Average Title & Text Lengths for Real & Fake News")
plt.ylabel("Average Length (characters)")
plt.xticks(rotation=45)
plt.show()